version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: bizflow_db
    restart: always
    environment:
      POSTGRES_DB: bizflow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d bizflow_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  cache:
    image: redis:7-alpine
    container_name: bizflow_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  adminer:
    image: adminer:latest
    container_name: bizflow_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bizflow_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started

  backend:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: bizflow_backend
    restart: always
    ports:
      - "5178:5178"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: >
      bash -c " dotnet tool install -g dotnet-ef || true; export PATH=\"$$PATH:/root/.dotnet/tools\"; dotnet ef migrations add AddUserHRFields_Migration --project src/BizFlow.Infrastructure --startup-project src/BizFlow.WebApi --output-dir Persistence/Migrations || true; dotnet ef database update --project src/BizFlow.Infrastructure --startup-project src/BizFlow.WebApi || true; dotnet watch run --non-interactive --project src/BizFlow.WebApi --urls=http://0.0.0.0:5178 > /app/backend-log.txt 2>&1 "
    environment:
      - ConnectionStrings__DefaultConnection=Host=aws-1-ap-northeast-2.pooler.supabase.com;Port=5432;Database=postgres;Username=postgres.nltybanibdbuxowimrpv;Password=nhatanh3008;SSL Mode=Require;Trust Server Certificate=true
      - ConnectionStrings__RedisConnection=cache:6379
      - DOTNET_USE_POLLING_FILE_WATCHER=1

    depends_on:
      cache:
        condition: service_started

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: bizflow_ai_service
    restart: always
    ports:
      - "8000:8000"
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./ai-service:/app

volumes:
  pgdata:
  redisdata:

