CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE subscription_plans (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Price" numeric(15,2) NOT NULL,
        "DurationMonths" integer NOT NULL,
        "Description" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_subscription_plans" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE tenants (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "TaxCode" text,
        "OwnerName" text NOT NULL,
        "Address" text,
        "Phone" text,
        "SubscriptionPlanId" integer,
        "IsActive" boolean NOT NULL,
        "CogsMethod" integer NOT NULL DEFAULT 0,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_tenants" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_tenants_subscription_plans_SubscriptionPlanId" FOREIGN KEY ("SubscriptionPlanId") REFERENCES subscription_plans ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE accounting_entries (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "TransactionDate" timestamp with time zone NOT NULL,
        "DocumentType" text NOT NULL,
        "DocumentRefId" text,
        "AccountCategory" text NOT NULL,
        "Amount" numeric(15,2) NOT NULL,
        "Description" text,
        CONSTRAINT "PK_accounting_entries" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_accounting_entries_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE cash_transactions (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "Type" text NOT NULL,
        "PaymentMethod" text NOT NULL DEFAULT 'Cash',
        "Amount" numeric(15,2) NOT NULL,
        "TransactionDate" timestamp with time zone NOT NULL,
        "TransactionCode" text NOT NULL,
        "Reason" text,
        "ReferenceDocument" text,
        "RelatedUserId" uuid,
        "PayerReceiverName" text,
        "Address" text,
        "AttachedDocuments" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_cash_transactions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_cash_transactions_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE categories (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "Name" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "Color" text,
        "ParentId" integer,
        CONSTRAINT "PK_categories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_categories_categories_ParentId" FOREIGN KEY ("ParentId") REFERENCES categories ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_categories_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE customers (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "Fullname" text NOT NULL,
        "Phone" text,
        "TotalDebt" numeric(15,2) NOT NULL,
        "DebtLimit" numeric(15,2) NOT NULL DEFAULT 10000000.0,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_customers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_customers_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE expense_records (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "Category" text NOT NULL,
        "Amount" numeric(15,2) NOT NULL,
        "ExpenseDate" timestamp with time zone NOT NULL,
        "Description" text,
        "ReferenceDocument" text,
        "RelatedUserId" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_expense_records" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_expense_records_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE stores (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "Name" text NOT NULL,
        "Address" text,
        "Phone" text,
        "TaxCode" text,
        "Email" text,
        "LogoUrl" text,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "EnableVat" boolean NOT NULL DEFAULT FALSE,
        "DefaultVatRate" text NOT NULL DEFAULT '10',
        "AvailableVatRates" text NOT NULL DEFAULT '0,5,8,8.5,10,KCT',
        CONSTRAINT "PK_stores" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_stores_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE tax_obligations (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "TaxType" text NOT NULL,
        "Year" integer NOT NULL,
        "Month" integer NOT NULL,
        "AmountDue" numeric(15,2) NOT NULL,
        "AmountPaid" numeric(15,2) NOT NULL,
        "DueDate" timestamp with time zone,
        "Note" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_tax_obligations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_tax_obligations_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE users (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "Username" text NOT NULL,
        "PasswordHash" text NOT NULL,
        "Fullname" text NOT NULL,
        "Role" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "Phone" text,
        "IdentityCard" text,
        "DateOfBirth" timestamp with time zone,
        "JoinDate" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "SocialInsuranceNo" text,
        "HealthInsuranceNo" text,
        "PersonalTaxCode" text,
        "BasicSalary" numeric,
        "BankAccountNumber" text,
        "BankName" text,
        "NumberOfDependents" integer,
        "AvatarUrl" text,
        CONSTRAINT "PK_users" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_users_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE products (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "CategoryId" integer,
        "Code" text,
        "Name" text NOT NULL,
        "Description" text,
        "BaseUnit" text NOT NULL,
        "StockQuantity" numeric NOT NULL,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
        "CreatedAt" timestamp with time zone NOT NULL,
        "VatRate" text NOT NULL DEFAULT '10',
        "PriceIncludesVat" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_products" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_products_categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES categories ("Id"),
        CONSTRAINT "FK_products_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE audit_logs (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Action" text NOT NULL,
        "EntityName" text NOT NULL,
        "EntityId" text NOT NULL,
        "Timestamp" timestamp with time zone NOT NULL,
        "Details" text NOT NULL,
        CONSTRAINT "PK_audit_logs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_audit_logs_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_audit_logs_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE inventory_receipts (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "ReceiptCode" text NOT NULL,
        "Type" text NOT NULL,
        "Date" timestamp with time zone NOT NULL,
        "TotalAmount" numeric(15,2) NOT NULL,
        "TotalVatAmount" numeric(18,2) NOT NULL DEFAULT 0.0,
        "Note" text,
        "DelivererReceiverName" text,
        "ReferenceDocumentNo" text,
        "ReferenceDocumentDate" timestamp with time zone,
        "ReferenceDocumentIssuer" text,
        "WarehouseLocation" text,
        "Status" integer NOT NULL DEFAULT 0,
        "CancelledAt" timestamp with time zone,
        "CancelledBy" uuid,
        "CancelReason" text,
        "CreatedBy" uuid,
        CONSTRAINT "PK_inventory_receipts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_inventory_receipts_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_inventory_receipts_users_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES users ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE orders (
        "Id" uuid NOT NULL,
        "Code" text,
        "TenantId" uuid NOT NULL,
        "CustomerId" uuid,
        "CreatedBy" uuid,
        "TotalAmount" numeric(15,2) NOT NULL,
        "TotalVatAmount" numeric(18,2) NOT NULL DEFAULT 0.0,
        "PaymentMethod" text NOT NULL,
        "Status" text NOT NULL,
        "OrderSource" text NOT NULL,
        "RawTranscript" text,
        "CustomerName" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_orders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_orders_customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES customers ("Id"),
        CONSTRAINT "FK_orders_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_orders_users_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES users ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE payroll_records (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Year" integer NOT NULL,
        "Month" integer NOT NULL,
        "BaseSalary" numeric(15,2) NOT NULL,
        "Allowances" numeric(15,2) NOT NULL,
        "Deductions" numeric(15,2) NOT NULL,
        "NetPay" numeric(15,2) NOT NULL,
        "IsPaid" boolean NOT NULL,
        "PaymentDate" timestamp with time zone,
        "Note" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_payroll_records" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_payroll_records_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_payroll_records_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE inventory_transactions (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "Type" text NOT NULL,
        "Quantity" numeric(15,4) NOT NULL,
        "PriceType" integer NOT NULL DEFAULT 0,
        "UnitPrice" numeric(18,4) NOT NULL DEFAULT 0.0,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" uuid,
        "Note" text,
        CONSTRAINT "PK_inventory_transactions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_inventory_transactions_products_ProductId" FOREIGN KEY ("ProductId") REFERENCES products ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_inventory_transactions_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_inventory_transactions_users_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES users ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE product_histories (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "ActionName" text NOT NULL,
        "ChangeDetails" text NOT NULL,
        "ActionBy" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_product_histories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_product_histories_products_ProductId" FOREIGN KEY ("ProductId") REFERENCES products ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE product_units (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProductId" uuid NOT NULL,
        "UnitName" text NOT NULL,
        "ConversionRate" numeric NOT NULL,
        "Price" numeric(15,2) NOT NULL,
        "IsDefault" boolean NOT NULL,
        CONSTRAINT "PK_product_units" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_product_units_products_ProductId" FOREIGN KEY ("ProductId") REFERENCES products ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE accounting_ledger_s2 (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "ReceiptId" uuid,
        "Date" timestamp with time zone NOT NULL,
        "Type" text NOT NULL,
        "QuantityIn" numeric(18,4) NOT NULL,
        "ValueIn" numeric(15,2) NOT NULL,
        "QuantityOut" numeric(18,4) NOT NULL,
        "ValueOut" numeric(15,2) NOT NULL,
        "QuantityBalance" numeric(18,4) NOT NULL,
        "ValueBalance" numeric(15,2) NOT NULL,
        CONSTRAINT "PK_accounting_ledger_s2" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_accounting_ledger_s2_inventory_receipts_ReceiptId" FOREIGN KEY ("ReceiptId") REFERENCES inventory_receipts ("Id"),
        CONSTRAINT "FK_accounting_ledger_s2_products_ProductId" FOREIGN KEY ("ProductId") REFERENCES products ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_accounting_ledger_s2_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE inventory_receipt_details (
        "Id" uuid NOT NULL,
        "ReceiptId" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "DocumentQuantity" numeric(18,4) NOT NULL DEFAULT 0.0,
        "Quantity" numeric(18,4) NOT NULL,
        "UnitPrice" numeric(15,2) NOT NULL,
        "TotalPrice" numeric(15,2) NOT NULL,
        "VatRate" text,
        "VatAmount" numeric(18,2) NOT NULL DEFAULT 0.0,
        CONSTRAINT "PK_inventory_receipt_details" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_inventory_receipt_details_inventory_receipts_ReceiptId" FOREIGN KEY ("ReceiptId") REFERENCES inventory_receipts ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_inventory_receipt_details_products_ProductId" FOREIGN KEY ("ProductId") REFERENCES products ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE debt_transactions (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "CustomerId" uuid NOT NULL,
        "OrderId" uuid,
        "Type" text NOT NULL,
        "Amount" numeric(15,2) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_debt_transactions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_debt_transactions_customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES customers ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_debt_transactions_orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES orders ("Id"),
        CONSTRAINT "FK_debt_transactions_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE TABLE order_items (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "ProductUnitId" integer,
        "Quantity" numeric(15,4) NOT NULL,
        "UnitPrice" numeric(15,2) NOT NULL,
        "TotalPrice" numeric(15,2) NOT NULL,
        "VatRate" text,
        "VatAmount" numeric(18,2) NOT NULL DEFAULT 0.0,
        CONSTRAINT "PK_order_items" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_order_items_orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES orders ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_order_items_product_units_ProductUnitId" FOREIGN KEY ("ProductUnitId") REFERENCES product_units ("Id"),
        CONSTRAINT "FK_order_items_products_ProductId" FOREIGN KEY ("ProductId") REFERENCES products ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_accounting_entries_TenantId" ON accounting_entries ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_accounting_ledger_s2_ProductId" ON accounting_ledger_s2 ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_accounting_ledger_s2_ReceiptId" ON accounting_ledger_s2 ("ReceiptId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_accounting_ledger_s2_TenantId_ProductId_Date" ON accounting_ledger_s2 ("TenantId", "ProductId", "Date" DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_audit_logs_TenantId" ON audit_logs ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_audit_logs_UserId" ON audit_logs ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_cash_transactions_TenantId" ON cash_transactions ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_categories_ParentId" ON categories ("ParentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_categories_TenantId" ON categories ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_customers_TenantId" ON customers ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_debt_transactions_CustomerId" ON debt_transactions ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_debt_transactions_OrderId" ON debt_transactions ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_debt_transactions_TenantId" ON debt_transactions ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_expense_records_TenantId" ON expense_records ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_inventory_receipt_details_ProductId" ON inventory_receipt_details ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_inventory_receipt_details_ReceiptId" ON inventory_receipt_details ("ReceiptId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_inventory_receipts_CreatedBy" ON inventory_receipts ("CreatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_inventory_receipts_TenantId" ON inventory_receipts ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_inventory_transactions_CreatedBy" ON inventory_transactions ("CreatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_inventory_transactions_ProductId" ON inventory_transactions ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_inventory_transactions_TenantId" ON inventory_transactions ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_order_items_OrderId" ON order_items ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_order_items_ProductId" ON order_items ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_order_items_ProductUnitId" ON order_items ("ProductUnitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_orders_CreatedBy" ON orders ("CreatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_orders_CustomerId" ON orders ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_orders_TenantId" ON orders ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_payroll_records_TenantId" ON payroll_records ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_payroll_records_UserId" ON payroll_records ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_product_histories_ProductId" ON product_histories ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_product_units_ProductId" ON product_units ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_products_CategoryId" ON products ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_products_TenantId" ON products ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_stores_TenantId" ON stores ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_tax_obligations_TenantId" ON tax_obligations ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_tenants_SubscriptionPlanId" ON tenants ("SubscriptionPlanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE INDEX "IX_users_TenantId" ON users ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    CREATE UNIQUE INDEX "IX_users_Username" ON users ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701060834_Baseline_v1') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260701060834_Baseline_v1', '8.0.6');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701120217_Phase3_RefactorHRFields') THEN
    CREATE TABLE employee_profiles (
        "Id" uuid NOT NULL,
        "IdentityCard" text,
        "DateOfBirth" timestamp with time zone,
        "JoinDate" timestamp with time zone,
        "SocialInsuranceNo" text,
        "HealthInsuranceNo" text,
        "PersonalTaxCode" text,
        "BasicSalary" numeric(15,2),
        "BankAccountNumber" text,
        "BankName" text,
        "NumberOfDependents" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_employee_profiles" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_employee_profiles_users_Id" FOREIGN KEY ("Id") REFERENCES users ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701120217_Phase3_RefactorHRFields') THEN

        -- Bước 1: Migrate ALL data & Tôn trọng Historical Audit (CreatedAt)
        INSERT INTO employee_profiles (
            "Id", "IdentityCard", "DateOfBirth", "JoinDate",
            "SocialInsuranceNo", "HealthInsuranceNo", "PersonalTaxCode", "BasicSalary",
            "BankAccountNumber", "BankName", "NumberOfDependents", "CreatedAt"
        )
        SELECT 
            "Id", "IdentityCard", "DateOfBirth", "JoinDate",
            "SocialInsuranceNo", "HealthInsuranceNo", "PersonalTaxCode", "BasicSalary",
            "BankAccountNumber", "BankName", "NumberOfDependents", "CreatedAt"
        FROM users
        ON CONFLICT ("Id") DO NOTHING;

        -- Bước 2: PK-Level Verification bằng PL/pgSQL
        DO $$
        DECLARE
            missing_count INT;
            mismatch_salary_count INT;
            mismatch_idcard_count INT;
            mismatch_taxcode_count INT;
        BEGIN
            SELECT COUNT(*)
            INTO missing_count
            FROM users u
            LEFT JOIN employee_profiles ep ON ep."Id" = u."Id"
            WHERE ep."Id" IS NULL;

            IF missing_count > 0 THEN
                RAISE EXCEPTION
                'MIGRATION FAILED: % users missing employee profile rows',
                missing_count;
            END IF;

            SELECT COUNT(*)
            INTO mismatch_salary_count
            FROM users u
            JOIN employee_profiles ep ON ep."Id" = u."Id"
            WHERE u."BasicSalary" IS DISTINCT FROM ep."BasicSalary";

            IF mismatch_salary_count > 0 THEN
                RAISE EXCEPTION
                'MIGRATION FAILED: % users have mismatched BasicSalary',
                mismatch_salary_count;
            END IF;

            SELECT COUNT(*)
            INTO mismatch_idcard_count
            FROM users u
            JOIN employee_profiles ep ON ep."Id" = u."Id"
            WHERE u."IdentityCard" IS DISTINCT FROM ep."IdentityCard";

            IF mismatch_idcard_count > 0 THEN
                RAISE EXCEPTION
                'MIGRATION FAILED: % users have mismatched IdentityCard',
                mismatch_idcard_count;
            END IF;

            SELECT COUNT(*)
            INTO mismatch_taxcode_count
            FROM users u
            JOIN employee_profiles ep ON ep."Id" = u."Id"
            WHERE u."PersonalTaxCode" IS DISTINCT FROM ep."PersonalTaxCode";

            IF mismatch_taxcode_count > 0 THEN
                RAISE EXCEPTION
                'MIGRATION FAILED: % users have mismatched PersonalTaxCode',
                mismatch_taxcode_count;
            END IF;
        END $$;

    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701120217_Phase3_RefactorHRFields') THEN
    ALTER TABLE users DROP COLUMN "BankAccountNumber";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701120217_Phase3_RefactorHRFields') THEN
    ALTER TABLE users DROP COLUMN "BankName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701120217_Phase3_RefactorHRFields') THEN
    ALTER TABLE users DROP COLUMN "BasicSalary";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701120217_Phase3_RefactorHRFields') THEN
    ALTER TABLE users DROP COLUMN "DateOfBirth";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701120217_Phase3_RefactorHRFields') THEN
    ALTER TABLE users DROP COLUMN "HealthInsuranceNo";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701120217_Phase3_RefactorHRFields') THEN
    ALTER TABLE users DROP COLUMN "IdentityCard";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701120217_Phase3_RefactorHRFields') THEN
    ALTER TABLE users DROP COLUMN "JoinDate";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701120217_Phase3_RefactorHRFields') THEN
    ALTER TABLE users DROP COLUMN "NumberOfDependents";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701120217_Phase3_RefactorHRFields') THEN
    ALTER TABLE users DROP COLUMN "PersonalTaxCode";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701120217_Phase3_RefactorHRFields') THEN
    ALTER TABLE users DROP COLUMN "SocialInsuranceNo";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701120217_Phase3_RefactorHRFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260701120217_Phase3_RefactorHRFields', '8.0.6');
    END IF;
END $EF$;
COMMIT;

